---
title: Assignment 3
output: html_notebook
---
```{r}

data <- read.csv("Assignment_3/Data/MPL.csv", na.strings = "NA")
median_MPL_01 <- median(data$MPL_conc[data$dose==0.1], na.rm=T)
median_MPL_01

median_MPL_03 <- median(data$MPL_conc[data$dose==0.3], na.rm=T)
median_MPL_03

medians <- aggregate(data[,c("MPL_conc","mRNA","Free_receptor")],list(data$dose,data$time), median, na.rm=T)
names(medians)[1:2] <- c("dose","time")
head(medians)

data_low_dose <- subset(data, dose != 0.3)
data_high_dose <- subset(data, dose != 0.1)

median_low_dose <- subset(medians, dose != 0.3)
median_high_dose <- subset(medians, dose != 0.1)
head(median_low_dose)
head(median_high_dose)
```
```{r}
library("deSolve")

D <- (median_MPL_01 * 1000)/374.471
parameters <- c(Ks_rm = 2.90, ic50_rm = 26.2, Kon = 0.00329, Kt = 0.63, Kre = 0.57, Rf = 0.49, Kd_R = 0.0572, Kd_Rm = 0.612, Ks_r = 3.22, D = D)
state <- c(Rmo = 4.74, Ro = 267, DR = 0, DRN = 0)
times <- seq(0, 168,  by = 1)

Grd_model <- function(t, y, parms){
  with(as.list(c(parms, y)),{
    Rmo.delta <- Ks_rm * (1-(DRN / (ic50_rm + DRN)))- Kd_Rm * Rmo
    R.delta <- Ks_r *  Rmo + Rf * Kre * DRN - Kon * D * Ro - Kd_R * Ro
    DR.delta <- Kon * D * Ro - Kt * DR
    DRN.delta <- Kt * DR - Kre * DRN

        return(list(c(Rmo.delta, R.delta, DR.delta, DRN.delta)))
       })
}

out <- ode(times = times, y = state,   parms = parameters, func = Grd_model, method = "euler")

plot(as.data.frame(out)$Rmo, type = "l", xlab = "Time in Hours", ylab = "Rmo concentration", ylim =  c(0.5,5.0))
lines(mRNA~time, data = median_low_dose, col = "blue")
points(mRNA~time, data = data_low_dose, col = "green")


plot(as.data.frame(out)$Ro, type = "l", xlab = "Time in Hours", ylab = "Ro concentration")
lines(Free_receptor~time, data = median_low_dose, col = "blue")
points(Free_receptor~time, data = data_low_dose, col = "green")

plot(as.data.frame(out)$DR, type = "l", xlab = "Time in Hours", ylab = "DR concentration")
lines(MPL_conc~time, data = median_low_dose, col = "blue")
points(MPL_conc~time, data = data_low_dose, col = "green")

plot(as.data.frame(out)$DRN, type = "l", xlab = "Time in Hours", ylab = "DRN concentration")



```
