---
title: "R Notebook"
output: html_document
---

The [R plugin](https://www.jetbrains.com/help/pycharm/r-plugin-support.html) for IntelliJ-based IDEs provides
handy capabilities to work with the [R Markdown](https://www.jetbrains.com/help/pycharm/r-markdown.html) files.
To [add](https://www.jetbrains.com/help/pycharm/r-markdown.html#add-code-chunk) a new R chunk,
```{r}
library("deSolve")

```
```{r}
# TODO fixe logical bug

# variables

tau_p <- 8.893084e+00
tau_b <- 1.793090e+01

A <- 1.15
B <- 0.08
C <- 0.1


parameters <- c(p       = 6.459494e-05, # fraction susceptible to bite
                alpha   = 1.904753e-03, # rate of bites
                beta    = 2.233049e+00, # between-host infection
                gamma_b = 2.293953e-01, # E to I
                gamma_p = 2.863875e-01, # E to I
                delta_b = 2.626527e-01, # recovery + death
                delta_p = 3.413748e-01, # recovery + death
                epsilon = 3.204494e-02, # I_b to I_p
                kk      = 1.105443e+00, # Imperfect intervention
                N       = 25570895     # population size
                )

S_b_0 <- as.numeric(parameters["N"]*parameters["p"])
S_p_0 <- as.numeric(parameters["N"] - S_b_0)

state <- c(Sb = S_b_0, Sy = S_p_0, Eb = 0, Ey =  0, Ib = 1, Ip = 1)

times <- seq(0, 70,  by = 0.1)

flea <- function (t){
  x <- A + B * sin((pi/180.) * t) + C * cos((pi/180.) * t )

  return (x)
}
intervention_p <- function (t){
  return (1. - 1./(parameters["kk"] + exp(tau_p - t)))
}
intervention_b <- function (t){
  return (1. - 1./(parameters["kk"] + exp(tau_b - t)))
}

deterministic_model <- function(t, y, parms){
  with(as.list(c(parms, y, t)),{
    delta.Sb <- -(alpha * flea(t) * intervention_b(t) * Sb) - (beta * intervention_p(t) * Sb * Ip/N)
    delta.Sy <- -(beta * intervention_p(t) * Sy * Ip/N)
    delta.Eb <- alpha * flea(t) * intervention_b(t)* Sb - gamma_b*Eb
    delta.Ey <- beta * intervention_p(t) * (Sb+Sy) * Ib/N - gamma_p*Ey
    delta.Ib <- gamma_b* Eb - epsilon * Ib - delta_b * Ib
    delta.Ip <- gamma_p* Ey + epsilon * Ib- delta_p * Ip


        return(list(c(delta.Sb, delta.Sy, delta.Eb, delta.Ey, delta.Ib, delta.Ip)))
       })
}

# Run the ode model and save the output to the out variable
out <- ode(times = times, y = state,   parms = parameters, func = deterministic_model, method = "euler")

plot(as.data.frame(out)$Eb, type = "l", xlab = "Time in Days", ylab = "Bubonice indices", col = "blue", ylim = c(0, 30))
plot(as.data.frame(out)$Ey, type = "l", xlab = "Time in Days", ylab = "Puneonic indices", col = "blue", ylim = c(0, 120))
plot(out)
```
