---
title: Assignment 2
output: html_notebook
---

# Opdracht week 2
## Maak in R Markdown:

## Schrijf een korte introductie over corticosteroiden, het gebruik ervan en het werkingsmechanisme.

## Beschrijf op basis van het model hoe de interactie verloopt tussen het geneesmiddel en de productie van receptor.

Glucocorticosteroids, also known as corticosteroids or simply steroids. Are a class of steroid hormones.
They are produced in the cortex of the adrenal glands and have a pivotal role in glucose, protein and fat metabolism of the body.
These steroids are of clinical & medicinal importance due to their anti-inflammatory, anti-allergic and immune-suppresive role in the body.
The main use of these steroids is however for anti-inflammatory therapy, as they are the most effective anti-flammatory therapy for asthma.
However, they are relatively ineffective in chronic obstructive pulmonary disease. This suppression of inflammation occurs via several molecular mechanisms.
Glucorticoids suppress the multiple inflammatory genes active in chronic inflammatory diseases, such as asthma, by reversing histone acetylation of activated inflammatory genes through binding of ligand-bound glucocorticoid receptors (GR) to co-activator molecules and recruitment of histone deacetylase-2 to the activated inflammatory gene transcription complex.
At higher concentrations of glucorticoids GR homodimers interact with DNA recognition sites to activate transcription through increased histone acetylation of anti-inflammatory genes and transcription of several genes linked to glucocorticoid side effects.

Sources: https://pubmed.ncbi.nlm.nih.gov/21198556/ , https://pubmed.ncbi.nlm.nih.gov/27796513/ , https://www.ncbi.nlm.nih.gov/books/NBK560897/

## Implementeer het model in R, waarbij je er van uit kunt gaan dat de concentratie MPL constant is (een parameter) en gelijk is aan 20 ng/mL. Denk er om dat de eenheid omgerekend moet worden om de vergelijkingen kloppend te maken. Dus 20 ng/ml * 1000 ml/L * 1 mol/ molgewicht g geeft nmol/L.

## Simuleer het model voor een duur van twee dagen. Let op: de snelheidsconstante is per uur, dus de tijdsframe moet hier rekening mee houden
```{r}
library("deSolve")

D <- (20 * 1000)/374.471
parameters <- c(Ks_rm = 2.90, ic50_rm = 26.2, Kon = 0.00329, Kt = 0.63, Kre = 0.57, Rf = 0.49, Kd_R = 0.0572, Kd_Rm = 0.612, Ks_r = 3.22, D = D)
state <- c(Rmo = 4.74, Ro = 267, DR = 0, DRN = 0)
times <- seq(0, 48,  by = 1)

Grd_model <- function(t, y, parms){
  with(as.list(c(parms, y)),{
    Rmo.delta <- Ks_rm * (1-(DRN / (ic50_rm + DRN)))- Kd_Rm * Rmo
    R.delta <- Ks_r *  Rmo + Rf * Kre * DRN - Kon * D * Ro - Kd_R * Ro
    DR.delta <- Kon * D * Ro - Kt * DR
    DRN.delta <- Kt * DR - Kre * DRN

        return(list(c(Rmo.delta, R.delta, DR.delta, DRN.delta)))
       })
}

out <- ode(times = times, y = state,   parms = parameters, func = Grd_model, method = "euler")

plot(out)
```

## Beschrijf de resultaten: Wat gebeurt er in de tijd en hoe kun je dit verklaren aan de hand van de interacties tussen de variabelen? Welke veranderingen treden op in (a) de concentratie vrije receptor, (b) de concentratie cytosol MPL-receptor complex, (c) de concentratie geactiveerd MPL-receptor complex, de totale concentratie receptoren en de concentratie receptor mRNA. Bepaal welke variabele het belangrijkst is voor de werking van het geneesmiddel en beschrijf deze in detail.

Er is te zien aan het begin dat er een grote hoeveelheid receptor mRNA en een hoge concentratie vrije receptor aanwezig zijn.
Naarmate de tijd neemt de receptor mRNA eerst af tot een laagte-punt waarna het stabiliseert op een waarde 1/3de van de top.
De concentratie vrije receptor wordt vrij snel omgezet tot cytosol MPL-receptor complexen en kort daarna ook tot geactiveerde MPL-receptor complexen in de nucleus.
Er is te zien in de grafieken dat de totale concentratie van receptoren nauwelijks of niet lijkt te veranderen. Echter, is wel te zien dat de concentratie
van receptor mRNA zich stabiliseert op een lagere concentratie.

Hieruit wordt geconcludeerd dat de belangrijkste waarde voor het geneesmiddel de concentratie van de vrije receptor is. Aangezien hieruit de complexen
worden geactiveerd en er geen nieuwe aanmaak van vrije receptoren te zien is in het model. Een hogere concentratie van vrije receptor
zou dan voor een sterkere inhibitie van ontstekingsfactoren zorgen.